version: "3"

services:
  postgres:
    image: postgres:13
    container_name: postgres-conntainer
    environment:
      - POSTGRES_USER=alfianhid
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=ny_taxi_data
    volumes:
      - "./postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432" 
    networks:
      - de-zoomcamp-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-conntainer
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      - "./pgadmin_data:/var/lib/pgadmin/data"
    ports:
      - "5050:5050"
    networks:
      - de-zoomcamp-network
    depends_on:
      - postgres-conntainer

networks:
  de-zoomcamp-network: